Rename variable coz Linux dotnet was saying error (in details)
BotLogic/ActionHandler.cs(153,43): error CS0136: A local or parameter named 'command' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter [/home/soliax/VFatumbot/VFatumbot.csproj]